import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowRight,
  faArrowRightToBracket,
  faArrowLeft,
  faBars,
  faBell,
  faBolt,
  faChartLine,
  faChess,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCircleNotch,
  faCirclePlay,
  faCoins,
  faDoorOpen,
  faEnvelope,
  faExplosion,
  faGift,
  faFeatherPointed,
  faGamepad,
  faGlobe,
  faLock,
  faMagnifyingGlass,
  faMeteor,
  faPuzzlePiece,
  faRocket,
  faSatellite,
  faShieldHalved,
  // faSparkles,
  faStar,
  faTrophy,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUsers,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { faDiscord, faGoogle } from '@fortawesome/free-brands-svg-icons'

library.add(
  faArrowRight,
  faArrowRightToBracket,
  faArrowLeft,
  faBars,
  faBell,
  faBolt,
  faChartLine,
  faChess,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCircleNotch,
  faCirclePlay,
  faCoins,
  faDoorOpen,
  faEnvelope,
  faExplosion,
  faGift,
  faFeatherPointed,
  faGamepad,
  faGlobe,
  faLock,
  faMagnifyingGlass,
  faMeteor,
  faPuzzlePiece,
  faRocket,
  faSatellite,
  faShieldHalved,
  // faSparkles,
  faStar,
  faTrophy,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUsers,
  faXmark,
  faDiscord,
  faGoogle,
)

export {}

